### ISSUE TITLE
Postman template

### ISSUE THREAD

**Issue by arlemi** [ryo-ma/covid19-japan-web-api#1]
Hey!

I found your project listed on the `awesome-coronavirus` list and thought it could be helpful to create a collection to make it easier for interested users to query your API, the collection is published here: 
https://documenter.getpostman.com/view/9215231/SzYaWe6h?version=latest

We're currently gathering a list of APIs around Covid-19 and would love to add yours if you'd allow us, you can check the current list here: https://github.com/postmanlabs/covid-19-apis

Also for now the collection is published under my name but I would be very happy to give you ownership if you'd prefer!

**Comment by ryo-ma** [comment]
Hi! @arlemi 
I think it's a very good idea.
It's okay to publish the postman template and the link.

**Comment by ryo-ma** [comment]
@arlemi 
Can you add this repository link to the README as well?
