### ISSUE TITLE
wrong API positives data

### ISSUE THREAD

**Issue by RuiHirano** [ryo-ma/covid19-japan-web-api#2]
## Details
output API data is wrong when running below positives command.

``` 
https://covid19-japan-web-api.now.sh/api/v1/positives
```

 {
    "date": "北海道",
    "prefecture": "国外（武漢市）",
    "residence_prefecture": "40代",
    "age": "女性",
    "gender": "来日観光客",
    "attribute": "北海道1",
    "prefecture_number": "渡航歴",
    "travel_or_contact": "中国（武漢）",
    "detail": "",
    "src": "https://www.mhlw.go.jp/stf/newpage_09158.html",
    "onset": "2020/01/26",
    "symptom": "1",
    "death_or_discharge_date": "",
    "comment1": "",
    "outcome": "",
    "outcome_src": "",
    "comment2": ""
  },
...

**Comment by TeepaBlue** [comment]
そもそもREADMEに挙げられている感染者情報のJSONファイルには"date"という要素がありません。恐らく発病した日時と思われる"onset"という要素があるので"date"は要らないのではないでしょうか。

**Comment by RuiHirano** [comment]
自分で定義しているjson形式ではなく「https://covid19-japan-web-api.now.sh/api/v1/positives
」にアクセスした結果ずれています。
https://github.com/ryo-ma/covid19-japan-web-api/blob/7082d5243aedc092acaa9263ada370f37958ed29/script/create_positive_detail.py#L10-L14
のCSVカラムと合っていないのが原因だと思います。
dateを削除していただけないでしょうか？

**Comment by TeepaBlue** [comment]
すみません、元となっているデータを確認したところ、カラムが発表日、確定日、都道府県となっていて、確定日が空データとなっていることからこの現象が発生していると思われます。dateはそのまま削除して大丈夫でしょうか。

**Comment by ryo-ma** [comment]
報告ありがとうございます。
元データのカラムに変更があったことが原因となっておりました。
取り急ぎ修正しました。
