### ISSUE TITLE
Data Sourcesから取得できていない

### ISSUE THREAD

**Issue by yuto51942** [ryo-ma/covid19-japan-web-api#25]
4/17の17:00頃から情報を取得できずAPIが更新されていないようです。

**Comment by yuto51942** [comment]
ディレクトリ、ファイル名が変更されたようです。
https://github.com/swsoyee/2019-ncov-japan/commit/66903c3a1c1165a2c022b5e6dc0f1ed7602e7716

**Comment by ryo-ma** [comment]
ありがとうございます。現在対応中です。

**Comment by ryo-ma** [comment]
ご報告ありがとうございます。
ディレクトリ変更に対応しました。
