### ISSUE TITLE
検査数もあると嬉しいです

### ISSUE THREAD

**Issue by mazarimono** [ryo-ma/covid19-japan-web-api#26]
はんなりPythonでは発表ありがとうございました。

都道府県ごとの検査データがあると嬉しいです。

**Comment by ryo-ma** [comment]
実は都道府県ごとの検査数は自治体ごとに更新が滞っていたりするためAPIに含めていなかったんです。
prefectures APIは本日時点のデータということで配信をしていたので。
京都府だと公式サイトでも現時点で16日で更新が止まっていたりなどという状況です。

データとしては取得できそうなので少しだけ検討はしてみます。

**Comment by mazarimono** [comment]
確かにそうですね（更新の滞り）。

私も京都のデータが欲しいなと思って、サイトを見ていると画像で当日分しかなかったりして取れていません。

もしできそうであればお願いいたします。

**Comment by ryo-ma** [comment]
pcrデータをprefectureAPIに追加しました
