### ISSUE TITLE
API Updata

### ISSUE THREAD

**Issue by a849173140** [ryo-ma/covid19-japan-web-api#30]
I noticed that the date of the total data of this API has not been updated for many days. Did the API stop updating?

**Comment by ryo-ma** [comment]
Thank you for the issue.
Perhaps source data has not been updated. I will inquiry source data repository about this issue.
https://github.com/swsoyee/2019-ncov-japan

**Comment by ryo-ma** [comment]
I have opened an issue in the source repository.
https://github.com/swsoyee/2019-ncov-japan/issues/475

**Comment by a849173140** [comment]
> I have opened an issue in the source repository.
> [swsoyee/2019-ncov-japan#475](https://github.com/swsoyee/2019-ncov-japan/issues/475)

Thank you very much

**Comment by ryo-ma** [comment]
I got this issue.
I need to update API to support following data.
https://github.com/swsoyee/2019-ncov-japan/blob/master/50_Data/MHLW/summary.csv

**Comment by ryo-ma** [comment]
I have updated Total API and Total history API.

**Comment by a849173140** [comment]
I got it. Thank you for your work.
