### ISSUE TITLE
キーの値の意味について

### ISSUE THREAD

**Issue by Hayao0819** [ryo-ma/covid19-japan-web-api#38]
`prefectures`の`lat`や`discharge`などの値の意味がわかりません。
他にもわからないキーが有るため全ての意味をドキュメントにまとめていただくことはできないでしょうか？

**Comment by ryo-ma** [comment]
ドキュメントの作成は未定ですが、元データ(https://github.com/swsoyee/2019-ncov-japan/blob/master/50_Data/MHLW/summary.csv) のカラム名とAPIのキー名は以下のような対応になっております。

https://github.com/ryo-ma/covid19-japan-web-api/blob/master/src/script/create_prefectures.py

```python
        prefectures.append({'id': int(prefecture_df['id']),
                            'name_ja': prefecture,
                            'name_en': prefecture_df['name-en'],
                            'lat': float(prefecture_df['lat']),
                            'lng': float(prefecture_df['lng']),
                            'population': int(prefecture_df['pop']),
                            'last_updated': last_updated,
                            'cases': int(summary['陽性者']),
                            'deaths': int(summary['死亡者']),
                            'pcr': int(summary['検査人数']),
                            'hospitalize': int(summary['入院中']),
                            'severe': int(summary['重症者']),
                            'discharge': int(summary['退院者']),
                            'symptom_confirming': int(summary['確認中']),
                            })
```

元データでも日本語訳されていないカラム名の
lat,lngはlatitude、longitudeの略で位置情報、
populationは人口のハズです。
last_updatedはそれぞれのデータの最終更新日を記載しています。

カラム名に関してさらに詳しく知りたい場合は元データの作者(https://github.com/swsoyee/2019-ncov-japan) に確認するのがいいと思います。

**Comment by Hayao0819** [comment]
ありがとうございます。
[このアドレス](https://covid19-japan-web-api.now.sh/api/v1/positives?prefecture=%E6%9D%B1%E4%BA%AC%E9%83%BD)からのキーは日本語訳が見つからないのですが、元データの作者様に問い合わせたほうが良いでしょうか？

**Comment by ryo-ma** [comment]
そのデータは以下のURLが元データとなっております。キー名は並び順に対応してます。
https://github.com/swsoyee/2019-ncov-japan/blob/master/50_Data/positiveDetail.csv

```
```

ただ、positivesの元データの更新が８ヶ月前から止まっておりますのでご注意ください。

**Comment by Hayao0819** [comment]
ありがとうございますm(_ _)m
