### ISSUE TITLE
"prefectures" の地方自治体の呼称を揃えて欲しい

### ISSUE THREAD

**Issue by miya** [ryo-ma/covid19-japan-web-api#4]
[prefectures](https://covid19-japan-web-api.now.sh/api/v1/prefectures)のAPIですが、北海道のみ「道」があり他は無いので "東京" => "東京都" 、"青森" => "青森県" のようにして頂けないでしょうか?

**Comment by ryo-ma** [comment]
ご連絡ありがとうございます。
その辺りの名称等は基本的には以下の元データに準拠するスタンスをとっております。
https://github.com/swsoyee/2019-ncov-japan

方法としてはそちら側のアプリで吸収していただくか、元データの方にissueまたはpull requestをしたいただく方がいいと考えております。

よろしくお願いします。

**Comment by miya** [comment]
ご返信ありがとうございます。
すみません、こちらの確認不足でした。

元データの方にissueを投げてみます！
